### ISSUE TITLE
not support jdk1.8?

### ISSUE THREAD

**Issue by timetravel-boy** [fcavallarin/burp-dom-scanner#2]
An error occurred while loading the extension, Any output or error messages generated are shown below
OutputErrors
java.lang.ClassNotFoundException: burp.BurpExtender
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)at java.lang.ClassLoader.loadClass(UnknownSource)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at burp.kke.a(Unknown Source)
at burp.kke.<init>(Unknown Source)
at burp.igf.a(Unknown Source)
at burp.gc.run(Unknown Source)
at java.lang.Thread.runn(Unknown Source)

**Comment by hughink** [comment]
我也遇到了相同的问题

**Comment by fcavallarin** [comment]
What version of Burp are you using?
